### ISSUE TITLE
Images on CDN?

### ISSUE THREAD

**Issue by lorensr** [arvida/emoji-cheat-sheet.com#208]
Are they currently on one? If not, would be a nice feature.

**Comment by weilaihui** [comment]
:thumbsup:

**Comment by arvida** [comment]
Yes. 

Everything is served from AWS CloudFront :smile:

**Comment by lorensr** [comment]
To clarify, I mean for others to use. Are you saying that URLs of the form:

`http://www.emoji-cheat-sheet.com/graphics/emojis/bowtie.png`

are served by cloudfront and it's fine for other sites/apps who want to use this emoji library to use those URLs?

**Comment by arvida** [comment]
At its current form it is not meant for that. That is just the structure used by the web site and it can change without notice. So I wouldn't recommend using it as a CDN.
