### ISSUE TITLE
Shamelessly asking for a small few more :-)

### ISSUE THREAD

**Issue by devrich78** [arvida/emoji-cheat-sheet.com#212]
I would love to have the same style as :one: through :nine: also have A ~ F in uppercase for those of us who use hexidecimal all the time and would like to use that style for things like CSS color instructions :-)

**Comment by arvida** [comment]
Interesting idea :+1: 

However I am not the author of the actual emojis. The cheat sheet just list the emojis and their codes that work on the services. I think most of them use a implementation that is somewhat based on gemoji by GitHub (https://github.com/github/gemoji). I think that repo can be a good start for ideas like this.

**Comment by FF6918** [comment]
987654321
