### ISSUE TITLE
Emoji Cheat Sheet to Unicode Map?

### ISSUE THREAD

**Issue by JacobRYoung** [arvida/emoji-cheat-sheet.com#216]
Is there a list or map of the the emoji cheat sheet names to unicode characters readily available?

**Comment by JacobRYoung** [comment]
Found the solution to my own question. Here is a josh file with all unicode characters and aliases conveniently formatted https://github.com/github/gemoji/blob/master/db/emoji.json

**Comment by arvida** [comment]
:+1:
