### ISSUE TITLE
Please provide support for copy without flash

### ISSUE THREAD

**Issue by stof** [arvida/emoji-cheat-sheet.com#247]
Modern browsers don't need Flash anymore: http://zenorocha.github.io/clipboard.js/

**Comment by ruanmartinelli** [comment]
+1

**Comment by arvida** [comment]
Great idea! Haven't had the time to look in to this properly yet. Please do a pull request if you feel like it :wink:

**Comment by zenorocha** [comment]
+1 ;)

**Comment by mkautzmann** [comment]
:+1:

**Comment by arvida** [comment]
Resolved by #253

**Comment by aronwoost** [comment]
So awesome! Didn't even know that existed with flash before, since flash is click-to-play.

Thanks! :loudspeaker:

**Comment by stof** [comment]
@aronwoost there was already a message at the top telling you about this feature

**Comment by aronwoost** [comment]
@stof Come on, who reads the fu**ing manual? :wink:
