### ISSUE TITLE
Maybe add copying on click?

### ISSUE THREAD

**Issue by littleguga** [arvida/emoji-cheat-sheet.com#371]
For example using  https://github.com/zenorocha/clipboard.js/

How about this?

Also we can add checkbox for enabling/disabling this function.

In last chrome(win7) I need: select->ctrl+c

**Comment by rozzzly** [comment]
so [apparently](https://github.com/arvida/emoji-cheat-sheet.com/blob/7b34247653489d9e713cd1870d06c94b22237605/public/index.html#L104) they added this via `ZeroClipboard.swf`? but its broken, atleast for me


stacktrace
```
Error: Error: An invalid exception was thrown.
    at Error (native)
    at HTMLObjectElement.swf.(anonymous function) [as setHandCursor] (<anonymous>:19:32)
    at Rb (https://cdnjs.cloudflare.com/ajax/libs/zeroclipboard/2.2.0/ZeroClipboard.min.js:9:20399)
    at Function.kb (https://cdnjs.cloudflare.com/ajax/libs/zeroclipboard/2.2.0/ZeroClipboard.min.js:9:8397)
    at Function.Vb.focus.Vb.activate (https://cdnjs.cloudflare.com/ajax/libs/zeroclipboard/2.2.0/ZeroClipboard.min.js:9:23054)
    at HTMLDivElement.c (https://cdnjs.cloudflare.com/ajax/libs/zeroclipboard/2.2.0/ZeroClipboard.min.js:9:27031)"
```

so i tried to debug it a bit, but its minified, has messed source maps so yeah I don't want to spend any more time trying to debug it (>20 min already) it looks like some of the problem might have had to do with serving non https content on a https page, but I don't think that's it exactly. @arvida idk why you chose to use some swf --> jquery monstrosity... pure js is the way to go; simpler, and better cross-browser/mobile support. I'd probably just delete that crap and install @littleguga's suggestion or something else.

**Comment by littleguga** [comment]
@rozzzly I think we need to forget about flash(swf). It's insecure and a lot of users have disabled it.

**Comment by danbovey** [comment]
ZeroClipboard is actually how [GitHub implements](https://github.com/blog/1365-a-more-transparent-clipboard-button) copying to the clipboard which works in the majority of browsers.

**Comment by arvida** [comment]
Hi all,

Sorry for a late reply! Its been a bit hectic at my end 😊 This should be fixed now.

It looks like error might have to do with that the ZeroClipboard js was served from CDNJS. More info here: https://github.com/zeroclipboard/zeroclipboard/issues/632

Anyway, I made a temp fix and is serving the ZeroClipboard js from emoji-cheat-sheet.com for now. 

I agree that the long term fix is to use something else to get the copy functionality! I just haven't got around finding a good solution. Would be great if it worked in all major browsers. `clipboard.js` doesn't look to work in Safari. I solution might could be to use ZeroClipboard as a fallback for less savvy browsers.

**Comment by rozzzly** [comment]
now that I can _`click-to-copy`_ I feel quite spiffy :bowtie: 

@arvida 
As far as compatibility, I'd just like to point out something I often forget. Audience. This site is targeted towards computer savvy people, or at the very least people with the wherewithal to google for these _**`bbcode-esque`**_ emoji shortcodes--_I'm not sure of the proper term for those_. That being said, you probably shouldn't worry so much about compatibility; chances are, a significant majority of your visitors are running chrome, firefox, or a new-ish version of their OS' default browser.

The JS Clipboard API has a pretty decent adoption rate, considering the target devices of your users, that should be even better than the general population stats http://caniuse.com/#feat=clipboard

The only thing I might slightly worry about is mobile compatibility.. but JS is 100x more likely to work there than some fash thing.

**Comment by littleguga** [comment]
@rozzzly about mobile compatibility: iOS doesn't allow to copy anything to clipboard automatically. On Android everything is fine :)

**Comment by arvida** [comment]
True, well worth to investigate more! Chrome and FF is definitely the big browsers. Some browser stats from the last month:

|         Browser          |    Device     |    % of Total    | 
|-------------------|---------|--------| 
| Chrome            | desktop | 69.19% | 
| Firefox           | desktop | 11.29% | 
| Safari            | mobile  | 4.41%  | 
| Safari            | desktop | 3.92%  | 
| Chrome            | mobile  | 3.63%  | 
| Internet Explorer | desktop | 2.98%  | 
| Opera             | desktop | 1.06%  | 
| Safari            | tablet  | 0.69%  | 
| Edge              | desktop | 0.64%  | 
| Chrome            | tablet  | 0.32%  | 

If any of you guys want to do a pull request with another copy implementation, you are very welcome! :wink: Otherwise I will take a look at it when I get some time.

**Comment by rozzzly** [comment]
@littleguga  Safari + Opera has taken up IE's mantle :persevere:

@arvida 
> _"**when I get some time**"_
Same here man. Just now I imagined a mobile website interface:

> ```
>    _______________________________________
>   |                                       |
>   |                                       |
>   |                                       |
>   |                                       |
>   |                                       |
>   |                                       |
>   |                                       |
>
>
>
>
>
> ```
>
